services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuserpass
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d myappdb']
      interval: 1s
      timeout: 5s
      retries: 10

  nats-streaming:
    image: nats-streaming:0.25.5-linux
    command: ['-p', '4222', '-m', '8222', '--cluster_id', 'test-cluster']
    ports:
      - '4222:4222'
      - '8222:8222'

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: >
      -path /migrations
      -database postgres://myuser:myuserpass@postgres:5432/myappdb?sslmode=disable
      up
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - migrate
      - nats-streaming

volumes:
  postgres_data:
