version: '3.8'
services:
  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuserpass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  order-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - nats
      - postgres
    environment:
      DB_HOST: postgres   
      NATS_HOST: nats     